markdown: kramdown

# URL of the Site
url: 'https://ecodreams.github.io'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Ecodreams
# Description of the Site
description: Cojines aromáticos hechos con materiales reciclables
# URL of Image of the Site
site-image: https://ecodreams.github.io/assets/images/logo-ed.webp
# Keywords of the Site
site-keywords: pillow, almohada, eco, ecologico
# URL for the Image of custom Favicon
favicon-url: https://ecodreams.github.io/assets/images/logo-ed.webp

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://ecodreams.github.io/assets/images/woman-sleeping.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: ecodreams2025@gmail.com
instagram_username: ecodreams.ja
github_username:  ecodreams
whatsapp_number: +593958871930
tiktok_username: ecodreams.ja


# Google Analytics
google-analytics: /

# Name of the Author
author-name: EcoDreams
# URL for the Image of the Author
author-image: https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png
# 60 Words About the Author
author-about: En Eco Dreams creemos que el descanso y la sotenibilidad pueden ir de la mano.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/ecodreams

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
